name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    name: ${{ matrix.os }}_${{ matrix.boost }}_${{ matrix.compiler }}_${{ matrix.geos }}
    strategy:
      matrix:
        os: [ubuntu, macos]
        boost: [1_60, 1_66]
        geos: ['3.8.1', 'none']
        compiler: ['g++', 'g++-8', 'clang++']
        exclude:
          - os: macos
            boost: 1_60, 1_66
          - os: macos
            compiler: 'g++-8'
        include:
          - os: ubuntu
            boost: 1_66
            compiler: g++-8
            geos: '3.8.1'
            code_coverage: "--enable-code-coverage"
          - boost: 1_60
            skip_gerberimporter_tests: "SKIP_GERBERIMPORTER_TESTS=1"
    runs-on: ${{ matrix.os }}-latest

    steps:
    - name: Checkout pcb2gcode source
      uses: actions/checkout@v2
    - name: Setup paths and env
      run: |
        mkdir -p $HOME/.local/bin
        mkdir -p $HOME/.local/lib/pkgconfig
        echo "::set-env name=PKG_CONFIG_PATH::$HOME/.local/lib/pkgconfig:$PKG_CONFIG_PATH"
        echo "::set-env name=LD_LIBRARY_PATH::$HOME/.local/lib:$LD_LIBRARY_PATH"
        echo "::set-env name=PATH::$HOME/.local/bin:$PATH"
    - name: Linux specific setup
      if: matrix.os == 'ubuntu'
      run: |
        sudo apt-get update
        sudo apt-get install libgtkmm-2.4-dev moreutils autopoint libc6-dbg
        echo "::set-env name=NUM_CPUS::$((`nproc --all` * 4))"
    - name: Set clang as default compiler
      if: matrix.compiler == 'clang++'
      run: |
        echo "::set-env name=CC::`which clang`"
        echo "::set-env name=CXX::`which clang++`"
    - name: g++-8 specific setup
      if: matrix.compiler == 'g++-8'
      run: |
        sudo apt-get install g++-8
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 80 --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-7 --slave /usr/bin/gcov gcov /usr/bin/gcov-7
        sudo update-alternatives --set gcc /usr/bin/gcc-8
    - name: Macos specific setup
      if: matrix.os == 'macos'
      run: |
        brew update
        brew upgrade python@3.7
        brew reinstall -s libtool
        brew unlink parallel
        brew install boost gtkmm moreutils gettext librsvg autoconf automake pkg-config
        brew upgrade wget
        hash -r
        ln -f -s `which glibtoolize` $HOME/.local/bin/libtoolize
        ln -f -s `which glibtool` $HOME/.local/bin/libtool
        hash -r
     # echo "::set-env name=NUM_CPUS::$((`sysctl -n hw.logicalcpu` * 4))"
     #   echo "::set-env name=PKG_CONFIG_PATH::$PKG_CONFIG_PATH:/usr/local/opt/libffi/lib/pkgconfig"
     #   echo "::set-env name=CPPFLAGS_gerbv::-DQUARTZ"
     #   echo "::set-env name=PATH::/usr/local/opt/gettext/bin:$PATH"
    - name: Macos geos
      if: matrix.geos != 'none' && matrix.os == 'macos'
      run:
        brew install geos
    - name: Sanitize cache key
      id: sanitize-key
      run: echo "::set-output name=key::$(echo '${{ matrix.os }}_${{ matrix.boost }}_${{ matrix.compiler }}_${{ matrix.geos }}' | sed 's/+/plus/g')"
    - name: Cache .local
      uses: actions/cache@v1
      with:
        path: ~/.local
        key: ${{ steps.sanitize-key.outputs.key }}
    - name: Build and install boost
      if: matrix.os == 'ubuntu'
      env:
        BOOST: ${{ matrix.boost }}_0
      run: |
        if [ ! -d "${HOME}/.local/include/boost" ]; then
          pushd ~
          for i in {1..5}; do
            wget -q -T20 -t1 -O "boost_${BOOST}.tar.bz2" "https://github.com/pcb2gcode/pcb2gcode/releases/download/v2.0.0/boost_${BOOST}.tar.bz2" && break;
          done
          tar xjf "boost_${BOOST}.tar.bz2"
          pushd boost_${BOOST}
          ./bootstrap.sh --with-libraries=program_options --prefix=${HOME}/.local
          ./b2 -j ${NUM_CPUS}
          ./b2 install
          popd
          popd
        fi
        echo "::set-env name=BOOST_ROOT::$(echo ${HOME}/.local)"
    - name: Build and install geos
      if: matrix.os == 'ubuntu' && matrix.geos != 'none'
      env:
        GEOS: ${{ matrix.geos }}
      run: |
        if [ ! -d "${HOME}/.local/include/geos" ]; then
          pushd ~
          for i in {1..5}; do
            wget -q -T20 -t1 -O "geos-${GEOS}.tar.bz2" "http://download.osgeo.org/geos/geos-${GEOS}.tar.bz2" && break;
          done
          tar xjf "geos-${GEOS}.tar.bz2"
          pushd geos-${GEOS}
          ./configure --prefix=${HOME}/.local
          make -j ${NUM_CPUS}
          make install
          popd
          popd
        fi
    - name: coverage specific setup
      if: matrix.code_coverage
      run: |
        sudo apt-get install libperlio-gzip-perl libjson-perl
        pushd ~
        git clone --depth=1 https://github.com/linux-test-project/lcov.git
        pushd lcov
        make PREFIX=~/.local install
        hash -r
        lcov --version
    - name: Display information about build environment
      continue-on-error: true
      run: |
        env
        g++ --version
        clang++ --version
        pkg-config --version
        m4 --version
    - name: Install gerbv
      run: |
        if ! gerbv --version; then
          pushd ~
          git clone --depth=1 https://github.com/eyal0/gerbv.git
          pushd gerbv
          sh autogen.sh
          ./configure CPPFLAGS=$CPPFLAGS_gerbv --disable-update-desktop-database --prefix=${HOME}/.local
          make -j ${NUM_CPUS}
          make install
          popd
          popd
        fi
    - name: Install valgrind
      if: matrix.os != 'macos'
      run: |
        if ! valgrind --version; then
          pushd ~
          git clone --depth=1 git://sourceware.org/git/valgrind.git
          pushd valgrind
          sh autogen.sh
          ./configure --prefix=${HOME}/.local
          make -j ${NUM_CPUS}
          make install
          popd
          popd
        fi
    - name: Install parallel
      run: |
        if ! parallel --version; then
          pushd ~
          for i in {1..5}; do
            wget -q -T5 -t1 -O "parallel-latest.tar.bz2" "http://ftpmirror.gnu.org/parallel/parallel-latest.tar.bz2" && break;
          done
          mkdir parallel
          pushd parallel
          tar xjf "../parallel-latest.tar.bz2"
          pushd parallel-*
          ./configure --prefix=${HOME}/.local
          make
          make install
          popd
          popd
          popd
        fi
    - name: Finalize setup
      run: |
        hash -r
    - name: Autoreconf pcb2gcode
      run: autoreconf -fvi
    - name: Configure pcb2gcode
      # pcb2gcode_CPPFLAGS_EXTRA=-Werror 
      # macos : -Wnolanguage-extension-token -DBOOST_GEOMETRY_DISABLE_DEPRECATED_03_WARNING
      run: >-
        export CPPFLAGS_EXTRA="-Werror"
        if [[ $RUNNER_OS == "macOS" ]]; then
          export CPPFLAGS_EXTRA="$CPPFLAGS_EXTRA -Wnolanguage-extension-token -DBOOST_GEOMETRY_DISABLE_DEPRECATED_03_WARNING"
        fi
        ./configure pcb2gcode_CPPFLAGS_EXTRA=$CPPFLAGS_EXTRA
        --disable-dependency-tracking
        --disable-silent-rules
        --enable-static-boost
        ${{ matrix.code_coverage }}
        || (cat config.log && false)
    - name: Remove debug flags from coverage builds
      if: matrix.code_coverage
      run: sed -i 's/-g /-g0 /g' Makefile
    - name: Make pcb2gcode
      run: make -j ${NUM_CPUS}
    - name: Run examples
      if: '! matrix.code_coverage'
      run: |
        pushd testing/gerbv_example
        ls | parallel -k -j ${NUM_CPUS} --halt soon,fail=1 '
          pushd {};
          echo "Running on {}";
          if [[ -f "no-valgrind" ]]; then
            cat no-valgrind;
          fi;
          if [[ -f "no-valgrind" || "${{ matrix.os }}" == "macos" ]]; then
            time ../../../pcb2gcode || exit;
          else
            time valgrind --error-exitcode=127 --errors-for-leak-kinds=definite --leak-check=full -- ../../../pcb2gcode || exit;
          fi;
          popd'
        popd
    - name: Reset coverage
      if: matrix.code_coverage
      continue-on-error: true
      run: lcov --directory . -z
    - name: Run unit tests
      if: matrix.os == 'macos'
      env:
        VERBOSE: 1
        SKIP_GERBERIMPORTER_TESTS_PNG: 1
      run: ${{ matrix.skip_gerberimporter_tests }} make -j ${NUM_CPUS} check
    - name: Run unit tests with valgrind
      if: matrix.os != 'macos'
      env:
        VERBOSE: 1
        SKIP_GERBERIMPORTER_TESTS_PNG: 1
      run: ${{ matrix.skip_gerberimporter_tests }} make -j ${NUM_CPUS} check-valgrind
    - name: Run integration tests
      if: matrix.boost == '1_66' && matrix.geos == '3.8.1'
      run: |
        pip install --user wheel colour_runner unittest2 termcolor concurrencytest in_place
        ./integration_tests.py -j ${NUM_CPUS}
    - name: Gather coverage
      if: matrix.code_coverage
      run: |
        lcov --rc lcov_branch_coverage=1 -rc lcov_function_coverage --directory . --capture --no-external --output-file "pcb2gcode-lcov.info"
        lcov --rc lcov_branch_coverage=1 -rc lcov_function_coverage -r "pcb2gcode-lcov.info" '*_tests.cpp' -o "pcb2gcode-lcov.info"
    - name: Export coverage artifact
      if: matrix.code_coverage
      uses: actions/upload-artifact@v1
      with:
        name: lcov
        path: pcb2gcode-lcov.info
    - name: Upload coverage to coveralls
      if: matrix.code_coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: pcb2gcode-lcov.info
        parallel: true
  finalize-coverage:
    needs: build-and-test
    name: Finalize coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout pcb2gcode source
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Finalize coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
